# **All Required Imports**

In [116]:
from google.colab import drive
import numpy as np
import csv

from nltk.corpus import stopwords
from nltk import word_tokenize

import nltk
nltk.download('stopwords')

import re

import nltk
nltk.download('punkt')

from nltk.stem.wordnet import WordNetLemmatizer

import nltk
nltk.download('wordnet')

from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split

import pandas as pd

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.naive_bayes import MultinomialNB

# !pip install scipy
# !pip install KMeansSMOTE
from imblearn.over_sampling import ADASYN
from imblearn.over_sampling import (SMOTE, BorderlineSMOTE, SVMSMOTE, SMOTENC)
from imblearn.over_sampling import RandomOverSampler

from sklearn.svm import LinearSVC
from sklearn.datasets import make_classification
from sklearn import svm

from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score

from sklearn import svm
from sklearn.model_selection import GridSearchCV

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


# Data Load & Preprocessing

## Data Load from Google Drive

In [23]:
# load pima indians dataset
drive.mount('/content/drive')
src = '/content/drive/My Drive/Colab Notebooks/'


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [38]:
#reading csv file
datafile = open(src+'Job titles and industries.csv', 'r')
myreader = csv.reader(datafile)

# Processing Dataset into a Data Frame

job_title = []
industry  = []

for row in myreader:
  job_title.append(row[0])
  industry.append(row[1])

#delete first entry of all arrays
# as they're corresponding to 'job title','industry' header field
del job_title[0]
del industry[0]
  
#initializing data frame  
frame_data =  pd.DataFrame(job_title, columns=["job_title"])
frame_data["industry"] = industry


#Testing results
frame_data

job_title   industry
0     technical support and helpdesk supervisor - co...         IT
1                     senior technical support engineer         IT
2                                   head of it services         IT
3                                 js front end engineer         IT
4                      network and telephony controller         IT
5                   privileged access management expert         IT
6                   devops engineers x 3 - global brand         IT
7                   devops engineers x 3 - global brand         IT
8                                         data modeller         IT
9             php web developer £45,000 based in london         IT
10                  devops engineers x 3 - global brand         IT
11                  devops engineers x 3 - global brand         IT
12       solution / technical architect - ethical brand         IT
13                       lead developer - ethical brand         IT
14                           junior front-end developer         IT
15           vb .net web developer, milton keynes, £45k         IT
16                data scientist, newcastle, up to £40k         IT
17                                   senior bi engineer         IT
18                            machine learning engineer         IT
19              full stack developer, oxfordshire, £40k         IT
20           c# software developer, waltham cross, £55k         IT
21                                 senior data engineer         IT
22    erp support analyst - unit4, agresso business ...         IT
23    application support analyst - cheshire - finan...         IT
24    accountancy software trainer - manchester - re...         IT
25                                     business analyst         IT
26                                     business analyst         IT
27                                        delivery lead         IT
28    devops engineer x 2 temp - county buildings, a...         IT
29                        it change and problem analyst         IT
...                                                 ...        ...
8556                                wordpress developer  Marketing
8557                                    admin assistant  Marketing
8558                       digital marketing specialist  Marketing
8559                          digital marketing manager  Marketing
8560                                    telesales agent  Marketing
8561                                        sales agent  Marketing
8562                                        ceo/monufya  Marketing
8563                       graphic designer / finalizer  Marketing
8564                        admin & marketing executive  Marketing
8565                           digital media specialist  Marketing
8566                                     content writer  Marketing
8567           digital marketing specialist- internship  Marketing
8568                                       receptionist  Marketing
8569                             social media moderator  Marketing
8570                                  junior accountant  Marketing
8571                                    it system admin  Marketing
8572                                    telesales agent  Marketing
8573        business development specialist (part-time)  Marketing
8574                  sales account manager (part-time)  Marketing
8575                                      sales manager  Marketing
8576                marketing & social media specialist  Marketing
8577                               senior php developer  Marketing
8578                      social media graphic designer  Marketing
8579                        sponsorship sales executive  Marketing
8580                               marketing specialist  Marketing
8581                                   data entry clerk  Marketing
8582                                    content creator  Marketing
8583                          sales & marketing manager  Marketing
8584           marketing &

In [3]:
#### format of Data set & labels

## Data Set -> job title ,string, 1 entry /row
# i.e: IT_dataset 

## 4 array labels -> industry , 1/0 , 1 entry/row
#  IT,Marketing, Education, Accountancy



# datafile = open(src+'Job titles and industries.csv', 'r')
# myreader = csv.reader(datafile)

# dataset         = []

# #used in balancing dataset
# # IT_dataset         = []
# # Marketing_dataset  = []
# # Education_dataset  = []
# # Accountancy_dataset= []

# IT_labels          = []
# Marketing_labels   = []
# Education_labels   = []
# Accountancy_labels = []

# for row in myreader:
#   print(row)
  
#   dataset.append(row[0])
#   if row[1] == 'IT':
# #     IT_dataset.append(row[0])
#     IT_labels.append(1)
#   else:
#     IT_labels.append(0)
  
#   if row[1] == 'Marketing':
# #     Marketing_dataset.append(row[0])
#     Marketing_labels.append(1)
#   else:
#     Marketing_labels.append(0)
    
#   if row[1] == 'Education':
# #     Education_dataset.append(row[0])
#     Education_labels.append(1)
#   else:
#     Education_labels.append(0)
  
#   if row[1] == 'Accountancy':
# #     Accountancy_dataset.append(row[0])
#     Accountancy_labels.append(1)
#   else:
#     Accountancy_labels.append(0)
  

# #delete first entry of all arrays
# # as they're corresponding to 'job title','industry' header field

# del dataset[0]
# del IT_labels[0]
# del Marketing_labels[0]
# del Education_labels[0]
# del Accountancy_labels[0]
  
  
# ##convert them to numpy arrays

# dataset = np.array(dataset)

# IT_labels = np.array(IT_labels)          
# Marketing_labels = np.array(Marketing_labels)   
# Education_labels = np.array(Education_labels)   
# Accountancy_labels = np.array(Accountancy_labels)





['job title', 'industry']
['technical support and helpdesk supervisor - county buildings, ayr soa04086', 'IT']
['senior technical support engineer', 'IT']
['head of it services', 'IT']
['js front end engineer', 'IT']
['network and telephony controller', 'IT']
['privileged access management expert', 'IT']
['devops engineers x 3 - global brand', 'IT']
['devops engineers x 3 - global brand', 'IT']
['data modeller', 'IT']
['php web developer £45,000 based in london', 'IT']
['devops engineers x 3 - global brand', 'IT']
['devops engineers x 3 - global brand', 'IT']
['solution / technical architect - ethical brand', 'IT']
['lead developer - ethical brand', 'IT']
['junior front-end developer', 'IT']
['vb .net web developer, milton keynes, £45k', 'IT']
['data scientist, newcastle, up to £40k', 'IT']
['senior bi engineer', 'IT']
['machine learning engineer', 'IT']
['full stack developer, oxfordshire, £40k', 'IT']
['c# software developer, waltham cross, £55k', 'IT']
['senior data engineer', 'IT']

In [4]:
# ##testing
# print(dataset.shape)
# print(dataset[6467])

# print(IT_labels.shape)
# print(IT_labels[6467])

# print(Marketing_labels.shape)
# print(Marketing_labels[6467])

# print(Education_labels.shape)
# print(Education_labels[6467])

# print(Accountancy_labels.shape)
# print(Accountancy_labels[6467])

(8586,)
tutor jobs available - no experience required
(8586,)
0
(8586,)
0
(8586,)
1
(8586,)
0


## **Cleaning Dataset**

In [0]:
### Helper Functions

noise_list = set(stopwords.words("english"))
# noise detection
def remove_noise(input_text):
    words = word_tokenize(input_text)
    noise_free_words = list()
    i = 0;
    for word in words:
        if word.lower() not in noise_list:
            noise_free_words.append(word)
        i += 1
    noise_free_text = " ".join(noise_free_words)
    return noise_free_text

def lemetize_words(input_text):
    words = word_tokenize(input_text)
    new_words = []
    lem = WordNetLemmatizer()
    for word in words:
        word = lem.lemmatize(word, "v")
        new_words.append(word)
    new_text = " ".join(new_words)
    return new_text

def remove_special_keywords(input_text):
  special_keyword_list = ["county", "build", "ayr", "soa", "x", "global", "brand", "london", "k",
                          "contract", "day", "days", "qa", "paris", "france", "experience",
                          "require", "months", "fix", "term", "work", "per", "week", "hour",
                          "multinational", "company", "salary", "spanish", "opportunity",
                          "british", "firm", "visa", "available", "citizen", "start", "immediate", 
                          "eh", "amsterdam", "netherlands", "travel", "cayman", "islands", "tax", 
                          "free", "month", "hr", "kingston", "western", "europe", "oxford", "pr",
                          "b", "w", "saas", "deep", "executive", "abu", "dhabi", "dubai", "kuwait", 
                          "september", "uk", "full", "time", "india", "th", "october"]
  
   words = word_tokenize(input_text)
    noise_free_words = list()
    i = 0;
    for word in words:
        if word.lower() not in special_keyword_list:
            noise_free_words.append(word)
        i += 1
    noise_free_text = " ".join(noise_free_words)
    return noise_free_text
  
#### Main Function 
## cleaning 'job_title' records in a new column 
##in data frame:'cleaned_job_title'  

def dataset_cleaning(dataset):
    corpus = []
    
    for line in dataset["job_title"]:
        
        #transform all record into lower case
        review = re.sub('[^a-zA-Z]', ' ', line)
        review = review.lower()
         
        # remove non segnificant words
        #i.e: am, is, are ..ect
        review = remove_noise(review)
        
        #Lexicon Normalization: Lematization
        review = lemetize_words(review)
        
        #remove special keywords -> to do later
        review = remove_special_keywords(review)
        
        corpus.append(review)
    dataset["cleaned_job_title"] = corpus
    return
  
    

In [40]:
## cleaning Data frame
dataset_cleaning(frame_data)


## Testing
frame_data


job_title  ...                                  cleaned_job_title
0     technical support and helpdesk supervisor - co...  ...  technical support helpdesk supervisor county b...
1                     senior technical support engineer  ...                  senior technical support engineer
2                                   head of it services  ...                                       head service
3                                 js front end engineer  ...                              js front end engineer
4                      network and telephony controller  ...                       network telephony controller
5                   privileged access management expert  ...                 privilege access management expert
6                   devops engineers x 3 - global brand  ...                     devops engineer x global brand
7                   devops engineers x 3 - global brand  ...                     devops engineer x global brand
8                                         data modeller  ...                                      data modeller
9             php web developer £45,000 based in london  ...                      php web developer base london
10                  devops engineers x 3 - global brand  ...                     devops engineer x global brand
11                  devops engineers x 3 - global brand  ...                     devops engineer x global brand
12       solution / technical architect - ethical brand  ...         solution technical architect ethical brand
13                       lead developer - ethical brand  ...                       lead developer ethical brand
14                           junior front-end developer  ...                         junior front end developer
15           vb .net web developer, milton keynes, £45k  ...               vb net web developer milton keynes k
16                data scientist, newcastle, up to £40k  ...                         data scientist newcastle k
17                                   senior bi engineer  ...                                 senior bi engineer
18                            machine learning engineer  ...                             machine learn engineer
19              full stack developer, oxfordshire, £40k  ...                 full stack developer oxfordshire k
20           c# software developer, waltham cross, £55k  ...               c software developer waltham cross k
21                                 senior data engineer  ...                               senior data engineer
22    erp support analyst - unit4, agresso business ...  ...    erp support analyst unit agresso business world
23    application support analyst - cheshire - finan...  ...  application support analyst cheshire financial...
24    accountancy software trainer - manchester - re...  ...  accountancy software trainer manchester remote...
25                                     business analyst  ...                                   business analyst
26                                     business analyst  ...                                   business analyst
27                                        delivery lead  ...                                      delivery lead
28    devops engineer x 2 temp - county buildings, a...  ...        devops engineer x temp county build ayr soa
29                        it change and problem analyst  ...                             change problem analyst
...                                                 ...  ...                                                ...
8556                                wordpress developer  ...                                wordpress developer
8557                                    admin assistant  ...                                    admin assistant
8558                       digital marketing specialist  ...                          digital market specialist
8559                          digital marketing manager  ...                             digital market manager
8560          

In [8]:

# cleaned_dataset = np.array(cleaned_dataset)
# print(dataset[6406])
# print(cleaned_dataset[6406])

cover supervisor - northfield - up to £80 a day
cover supervisor northfield day


# **Classification Model**

## **Feature Engineering on Text**

In [0]:
## Extract features with count vectorizer

corpus = frame_data["cleaned_job_title"]

vectorizer = CountVectorizer(min_df=1)

X = vectorizer.fit_transform(corpus).toarray()


In [42]:
#Testing

print (X.shape)
X

(8586, 1804)


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [43]:
#Testing

vectorizer.get_feature_names()[:25]



['aat',
 'aberdeen',
 'aberfoyle',
 'abingdon',
 'abroad',
 'abu',
 'aca',
 'academic',
 'academy',
 'acca',
 'acccount',
 'access',
 'accommodation',
 'account',
 'accountancy',
 'accountant',
 'achieve',
 'acquisition',
 'active',
 'activities',
 'actuarial',
 'acute',
 'ad',
 'additional',
 'admin']

## **Label List Extraction**

In [0]:
## Extract Y list containing  

categories = frame_data["industry"].unique()
category_dict = {value:index for index, value in enumerate(categories)}


Y = frame_data["industry"].map(category_dict)


In [45]:
#Testing

category_dict

{'Accountancy': 3, 'Education': 2, 'IT': 0, 'Marketing': 1}

In [64]:
#Testing

print(len(Y))

print(Y[6410])

8586
2


## **Splitting Dataset into Train & Test**

In [0]:
## split dataset to 80-20 Train-Test

x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=1, )


In [54]:
#Testing

print(len(x_train))

print(len(x_test))

print(len(y_train))

print(len(y_test))


6868
1718
6868
1718


## **Balancing Datset**

In [0]:
#### oversampling low frequency samples

## should oversample after vectorizing the text data but before fitting the classifier

## Technique used:  SMOTE algorithm

##By oversampling only on the training data, none of the information in the validation data
##is being used to create synthetic observations. So these results should be generalizable


smote_nc = SMOTENC(categorical_features=[0, 3], random_state=0)
x_train_res, y_train_res = smote_nc.fit_resample(x_train, y_train)


In [74]:
print (np.bincount(y_train), np.bincount(y_train_res) )

[3797 1600 1175  296] [3797 3797 3797 3797]


## **Multinomial Naive Bayes Classifier**

In [75]:

clf = MultinomialNB()

clf.fit(x_train, y_train)

clf.score(x_test, y_test)

0.9173457508731082

In [76]:
y_test

3271    0
3153    0
5761    0
6751    2
6481    2
7629    2
4168    0
2458    0
7250    3
4220    0
5212    1
4966    1
7151    2
3005    0
3080    0
7211    3
5036    1
7372    3
5191    1
4793    1
2768    0
5502    1
3851    0
7163    2
911     0
6072    1
3085    0
2253    0
4653    1
3722    0
       ..
6181    1
823     0
3565    0
8230    1
1422    0
7899    2
5001    1
2657    0
724     0
3350    0
2351    0
7190    3
3953    0
3472    0
2210    0
4593    1
4879    1
702     0
203     0
2524    0
7696    2
5789    0
1882    0
2583    0
4536    1
589     0
5590    0
1885    0
1132    0
372     0
Name: industry, Length: 1718, dtype: int64

In [80]:
val = clf.predict(x_test)
for x in val:
  print(x)

0
0
0
2
2
2
0
0
3
0
1
1
2
0
2
0
0
0
1
1
0
1
0
2
0
1
0
0
1
0
1
0
0
2
0
1
2
0
0
0
1
0
0
0
0
0
0
0
0
0
1
3
1
1
0
1
1
0
1
1
0
0
0
0
2
0
0
1
1
0
1
1
1
1
0
1
0
0
0
1
1
2
2
0
0
0
0
1
1
0
0
2
1
1
2
1
2
0
1
1
0
0
2
0
1
1
0
0
0
1
0
2
0
0
0
1
0
0
0
0
1
0
0
0
0
0
0
1
0
0
1
2
2
0
1
2
0
0
0
0
0
0
2
0
0
3
0
1
1
3
1
0
0
0
1
2
0
0
1
1
0
1
1
1
0
0
2
1
2
0
3
0
0
2
2
1
0
2
0
1
1
1
0
0
0
2
0
0
2
0
2
0
1
1
2
3
2
2
2
0
0
0
2
2
0
0
0
0
2
0
3
1
1
0
1
3
0
0
0
0
3
0
0
0
0
0
0
1
2
1
1
0
1
1
0
0
0
0
0
1
1
2
0
0
0
0
0
0
0
0
1
1
0
0
1
0
2
3
1
1
0
1
0
0
0
0
2
0
1
1
2
0
0
2
0
3
0
2
0
1
2
1
0
0
1
0
0
0
1
1
2
0
2
0
0
2
0
1
2
1
1
2
2
0
0
1
0
1
0
1
0
0
0
0
0
1
2
1
0
0
1
1
1
1
2
2
1
2
0
2
0
0
0
2
0
0
1
0
0
0
0
0
2
0
0
0
0
2
0
1
1
0
0
0
1
0
0
0
3
1
0
1
0
2
0
0
1
0
2
0
3
0
1
0
0
0
2
0
0
0
1
1
0
0
0
0
1
1
1
0
1
0
0
0
2
0
3
1
3
2
1
0
1
1
0
0
0
0
0
3
2
0
0
0
0
1
0
0
0
0
0
0
0
2
1
0
0
1
1
0
1
0
2
2
1
3
1
0
2
2
0
0
1
0
1
0
1
0
0
1
0
0
1
1
0
1
0
0
2
2
1
0
1
0
2
0
0
1
0
0
1
1
0
0
0
0
3
0
0
1
1
1
0
0
1
0
1
0
1
0
3
0
0
2
0
0
0
0
2
3


In [81]:
category_dict

{'Accountancy': 3, 'Education': 2, 'IT': 0, 'Marketing': 1}

## **Linear SVM Classifier**

In [0]:
### Hyperparameter Tunning
## more params to tune better the model

def svc_param_selection(X, y, nfolds):
    Cs = [0.001, 0.01, 0.1, 1, 10]
    gammas = [0.001, 0.01, 0.1, 1]
#     degrees = [0, 1, 2, 3, 4, 5, 6]
    
    param_grid = {
                  'C': Cs,
                  'gamma' : gammas
                 }
    
    grid_search = GridSearchCV(svm.SVC(kernel='linear'), param_grid, cv=nfolds)
    
    grid_search.fit(X, y)
    
    grid_search.best_params_
    return grid_search.best_params_

  
### Testing 

best_params = svc_param_selection(x_train,y_train,7)

print(best_params)

In [82]:
##fit the model to best params

clf = svm.SVC(kernel='linear', C=1)

clf.fit(x_train, y_train)

clf.score(x_test, y_test)


0.9313154831199069

In [84]:
y_test

3271    0
3153    0
5761    0
6751    2
6481    2
7629    2
4168    0
2458    0
7250    3
4220    0
5212    1
4966    1
7151    2
3005    0
3080    0
7211    3
5036    1
7372    3
5191    1
4793    1
2768    0
5502    1
3851    0
7163    2
911     0
6072    1
3085    0
2253    0
4653    1
3722    0
       ..
6181    1
823     0
3565    0
8230    1
1422    0
7899    2
5001    1
2657    0
724     0
3350    0
2351    0
7190    3
3953    0
3472    0
2210    0
4593    1
4879    1
702     0
203     0
2524    0
7696    2
5789    0
1882    0
2583    0
4536    1
589     0
5590    0
1885    0
1132    0
372     0
Name: industry, Length: 1718, dtype: int64

In [85]:
val = clf.predict(x_test)
for x in val:
  print(x)

0
0
0
2
2
2
0
0
3
0
1
1
2
0
0
3
0
0
1
1
0
1
0
2
1
1
0
0
1
0
1
0
0
2
0
1
2
0
0
0
1
0
0
0
0
0
0
0
0
0
1
3
1
0
0
1
1
0
1
1
0
0
0
0
2
0
0
1
1
0
0
1
1
0
0
1
0
0
0
1
1
2
2
0
0
0
0
1
1
0
0
0
1
1
0
1
2
0
1
1
0
0
0
0
1
1
0
0
0
1
0
2
0
0
0
0
0
0
0
0
1
0
0
0
0
0
0
1
0
0
2
2
2
0
1
2
0
0
0
0
0
0
2
0
0
3
0
1
0
3
1
0
0
0
1
2
0
0
1
1
0
1
1
1
0
0
2
1
2
0
3
0
0
2
2
1
0
2
0
1
1
1
0
0
0
2
0
0
2
0
2
0
1
1
2
3
2
2
2
0
0
0
2
2
0
0
0
0
2
0
3
1
1
0
1
3
0
0
0
0
3
0
0
0
0
0
0
1
2
1
1
0
1
1
0
0
0
0
0
1
1
2
0
0
0
0
0
0
0
0
1
1
0
0
1
0
2
3
1
1
0
1
0
0
0
0
1
0
1
1
2
0
0
0
3
3
0
0
0
1
2
1
0
0
1
0
0
0
1
1
2
0
2
0
0
2
0
1
2
1
1
2
2
0
0
1
0
1
0
1
0
0
0
0
0
1
2
1
0
0
1
1
1
1
2
2
1
2
0
2
0
0
0
2
0
0
1
0
0
0
0
0
2
0
0
0
0
2
0
1
1
0
0
0
1
0
0
0
1
1
0
3
0
2
0
2
3
0
2
0
3
0
1
0
0
0
2
0
0
0
1
1
0
0
0
0
1
0
1
0
1
0
0
0
2
0
3
1
0
2
1
0
1
3
0
0
0
0
0
3
2
0
0
0
1
1
0
0
0
0
0
0
0
2
1
3
0
0
1
0
1
0
2
2
1
3
1
0
2
2
0
0
1
0
1
0
3
0
0
1
0
0
1
1
0
1
0
0
2
2
0
0
1
0
2
0
0
1
0
0
1
1
0
0
0
0
2
0
0
1
1
1
0
0
1
0
1
0
1
0
3
0
0
2
0
0
0
0
2
0


# **Model Evaluation - Linear SVM**

## **Confusion Matrix**

In [88]:
confusion_matrix(y_test, val)

## the diagonal element in each col 
## provides the specific accuracy for each key

array([[925,  22,   0,   2],
       [ 33, 387,   5,   6],
       [ 15,  17, 225,   3],
       [ 11,   2,   2,  63]])

## **Accuracy Measure**

In [113]:
clf.score(x_test, y_test)

0.9313154831199069

## **F1 Measure**

In [90]:
f1_score(y_test, val, average=None)

array([0.95706156, 0.90104773, 0.91463415, 0.82894737])

## **Recall Measure**

In [91]:
recall_score(y_test, val, average=None)

array([0.97471022, 0.89791183, 0.86538462, 0.80769231])

## **Precision Measure**

In [92]:
precision_score(y_test, val, average=None)

array([0.94004065, 0.90420561, 0.96982759, 0.85135135])

## **Micro-Averaged Precision-Recall Graph**

In [0]:
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score


##predicted labels
y_score = classifier.decision_function(X_test)


# For each class
precision = dict()
recall = dict()
average_precision = dict()
for i in range(n_classes):
    precision[i], recall[i], _ = precision_recall_curve(Y_test[:, i],
                                                        y_score[:, i])
    average_precision[i] = average_precision_score(Y_test[:, i], y_score[:, i])

# A "micro-average": quantifying score on all classes jointly
precision["micro"], recall["micro"], _ = precision_recall_curve(Y_test.ravel(),
    y_score.ravel())
average_precision["micro"] = average_precision_score(Y_test, y_score,
                                                     average="micro")
print('Average precision score, micro-averaged over all classes: {0:0.2f}'
      .format(average_precision["micro"]))



plt.figure()
plt.step(recall['micro'], precision['micro'], color='b', alpha=0.2,
         where='post')
plt.fill_between(recall["micro"], precision["micro"], alpha=0.2, color='b',
                 **step_kwargs)

plt.xlabel('Recall')
plt.ylabel('Precision')
plt.ylim([0.0, 1.05])
plt.xlim([0.0, 1.0])
plt.title(
    'Average precision score, micro-averaged over all classes: AP={0:0.2f}'
    .format(average_precision["micro"]))


# Model Testing

In [112]:
### given an input predict the correct class

def model_test(text_input):
  vec_text = vectorizer.transform(text_input).toarray()
  #using linear SVM because more accurate
  search_label = list(category_dict.values()).index(clf.predict(vec_text)[0])
  for name, index in category_dict.items():   
    if index == search_label:
        return name


### Testing
test = []
text = input("Enter Job Title : ")
test.append(text)
val = model_test(test)
print("Result: ",val)


Enter Job Title : software Engineer
Result:  IT
